### ISSUE TITLE
TypeError in PanoptesObject.save()

### ISSUE THREAD

**Issue by astopy** [zooniverse/panoptes-python-client#75]
```
Traceback (most recent call last):

 File "/Users/Shared/Library/Frameworks/Python.framework/Versions/2.7/bin//panoptes", line 9, in <module>

   load_entry_point('panoptescli==0.3', 'console_scripts', 'panoptes')()

 File "/Users/Shared/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py", line 722, in __call__

   return self.main(*args, **kwargs)

 File "/Users/Shared/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py", line 697, in main

   rv = self.invoke(ctx)

 File "/Users/Shared/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py", line 1066, in invoke

   return _process_result(sub_ctx.command.invoke(sub_ctx))

 File "/Users/Shared/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py", line 1066, in invoke

   return _process_result(sub_ctx.command.invoke(sub_ctx))

 File "/Users/Shared/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py", line 895, in invoke

   return ctx.invoke(self.callback, **ctx.params)

 File "/Users/Shared/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py", line 535, in invoke

   return callback(*args, **kwargs)

 File "/Users/Shared/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/panoptes_cli/commands/subject_set.py", line 83, in upload_subjects

   subject.save()

 File "/Users/Shared/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/panoptes_client/subject.py", line 32, in save

   response = super(Subject, self).save()

 File "/Users/Shared/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/panoptes_client/panoptes.py", line 534, in save

   self.raw['id'] = response[self._api_slug][0]['id']

TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by astopy** [comment]
Closing for now as I can't find a way to reproduce this.
